spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432
    username: postgres
    password: myfirstproject
  servlet:
    multipart:
      max-file-size: 50MB

# S3 config
s3:
  accessKey:
  secretKey:
  bucketName:
